### ISSUE TITLE
Create & upload documentation (31.07.2020)

### ISSUE THREAD

**Issue by johannesstroebele91** [Fleet-Analytics-Dashboard/Application#49]
_Information from professor Kirenz:_

- [x] Home
- [x] Goals
- [x] Solution Approach: show work process and progress; CRISP-DM https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining
- [x] Research
- [x] Design concept
- [x] !!! Maintenance Calender!!! @lj025 
- [x] Data Science @ts170 
- [x] Technology stack @ts170 
- [x] Dashboard Explanation @everbody
- [x] Lessons Learned @everbody
- [x] Potential Improvements: next steps (future scope) @everbody

**Comment by lj025** [comment]
![WhatsApp Image 2020-07-24 at 20 47 45](https://user-images.githubusercontent.com/40471100/88448587-a84b7380-ce3f-11ea-9799-dbf9a3413bbe.jpeg)
